name: Build and deploy Node.js app to Heroku

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latestild
    environment:
      name: "Production"

    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          slot-name: "Production"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
