name: Testing, build and deploy production to Heroku

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_URL: ${{ secrets.URL }}
        envkey_PORT: ${{ secrets.PORT }}
        envkey_DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        envkey_CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
        envkey_API_KEY: ${{ secrets.API_KEY }}
        envkey_API_SECRET: ${{ secrets.API_SECRET }}
        envkey_URL_CYPRESS: ${{ secrets.URL_CYPRESS }}
        envkey_LOGIN_CYPRESS: ${{ secrets.LOGIN_CYPRESS }}
        envkey_USER_ADMIN_CYPRESS: ${{ secrets.USER_ADMIN_CYPRESS }}
        envkey_PASS_ADMIN_CYPRESS: ${{ secrets.PASS_ADMIN_CYPRESS }}
        envkey_USER_CUSTOMER_CYPRESS: ${{ secrets.USER_CUSTOMER_CYPRESS }}
        envkey_PASS_CUSTOMER_CYPRESS: ${{ secrets.PASS_CUSTOMER_CYPRESS }}
        envkey_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        envkey_ADMIN_LOGIN_URL: ${{ secrets.ADMIN_LOGIN_URL}}

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        start: npm start
        browser: chrome
        headed: true
        wait-on: ${{ secrets.URL_CYPRESS }}
        wait-on-timeout: 120
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: cypress
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present

      - name: "Deploy production to Heroku"
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          slot-name: "Production"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'voucher4u'
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
