name: Build and deploy staging voucher to Heroku

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_URL: ${{ secrets.URL }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          envkey_CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_API_SECRET: ${{ secrets.API_SECRET }}
          envkey_LOGIN_CYPRESS: ${{ secrets.LOGIN_CYPRESS }}
          envkey_USER_ADMIN_CYPRESS: ${{ secrets.USER_ADMIN_CYPRESS }}
          envkey_PASS_ADMIN_CYPRESS: ${{ secrets.PASS_ADMIN_CYPRESS }}
          envkey_USER_CUSTOMER_CYPRESS: ${{ secrets.USER_CUSTOMER_CYPRESS }}
          envkey_PASS_CUSTOMER_CYPRESS: ${{ secrets.PASS_CUSTOMER_CYPRESS }}
          envkey_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          envkey_ADMIN_LOGIN_URL: ${{ secrets.ADMIN_LOGIN_URL}}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "staging"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: "Deploy staging to Heroku"
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          slot-name: "Staging"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          package: .
