name: Build and deploy staging voucher to Heroku

on:
  push:
    branches:
      - staging

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_URL: ${{ secrets.URL }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          envkey_CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
          envkey_API_KEY: ${{ secrets.API_KEY }}
          envkey_API_SECRET: ${{ secrets.API_SECRET }}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "staging"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2

      - name: "Deploy staging to Heroku"
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          slot-name: "Staging"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'panda-voucher'
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
